# Generated by Django 5.0.6 on 2024-06-09 01:11

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('description_en', models.TextField()),
                ('description_es', models.TextField()),
                ('tags', models.CharField(help_text='Comma-separated. Example: Python,Flutter,etc', max_length=255)),
                ('icon', models.ImageField(upload_to=portfolio.models.get_project_path)),
                ('screenshot_1', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_project_path)),
                ('screenshot_2', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_project_path)),
                ('screenshot_3', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_project_path)),
                ('screenshot_4', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_project_path)),
                ('screenshot_5', models.ImageField(blank=True, null=True, upload_to=portfolio.models.get_project_path)),
                ('github', models.URLField(blank=True, null=True)),
                ('play_store', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
